### ISSUE TITLE
typing issue?

### ISSUE THREAD

**Issue by fiosmiles** [jhansche/pybirdbuddy#15]
``Hi there,

New user! Did a pip install of the latest, and getting typing errors -- any ideas why?

Python 3.8.2, win32

```
>>> from birdbuddy.client import BirdBuddy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\birdbuddy\client.py", line 13, in <module>
    from .exceptions import (
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\birdbuddy\exceptions.py", line 10, in <module>
    class GraphqlError(Exception):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\birdbuddy\exceptions.py", line 25, in GraphqlError
    def raise_errors(errors: list[dict]) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by jhansche** [comment]
The library has been tested with Python 3.9 and 3.10 only. Python 3.8 is likely not compatible.

Please update your Python version and let me know if that helps.
